### ISSUE TITLE
Suggestion: copy types install command

### ISSUE THREAD

**Issue by repository** [ntwigs/nopy#2]
Hi, recently found this extension and have found it pretty useful so far. :)

Something I thought could be useful is a feature to copy the install command for a package's types, for when they exist but are in a separate package

![image](https://user-images.githubusercontent.com/41586666/212821025-26bd88fc-07c5-4e9b-be17-facc715e4c32.png)

In this case, something to copy `npm i -D @types/eases`

**Comment by ntwigs** [comment]
Hi! That's wonderful, thank you 🎉 I've updated the package with type dependency buttons 🙏 Just waiting for Googles approval - but it should be automagically updated 🪄 

![image](https://user-images.githubusercontent.com/14088342/212985196-e86bc355-4894-49ae-b7b0-62fc1a9173b8.png)

**Comment by ntwigs** [comment]
@repository It's now released 🙏 Also made Nopy a lot smaller whilst I was at it 😛

![image](https://user-images.githubusercontent.com/14088342/213169347-0107135b-9111-42f6-a909-856b2ba2e1c6.png)
![image](https://user-images.githubusercontent.com/14088342/213169370-8b1dec9b-2e6f-45f8-ab34-45283c122015.png)
